# Generated by Django 5.1 on 2024-08-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugamehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='file_path',
        ),
        migrations.AddField(
            model_name='game',
            name='assets_folder',
            field=models.FileField(blank=True, null=True, upload_to='games/assets/'),
        ),
        migrations.AddField(
            model_name='game',
            name='js_file',
            field=models.FileField(blank=True, null=True, upload_to='games/js/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/images/'),
        ),
    ]
