# Generated by Django 5.1 on 2024-08-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nugamehub', '0002_remove_game_file_path_game_assets_folder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='assets_folder',
        ),
    ]
