# Generated by Django 5.1 on 2024-08-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nugamehub', '0003_rename_image_game_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
