# Generated by Django 5.1 on 2024-08-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('developing', 'Developing'), ('in_review', 'In Review'), ('published', 'Published')], default='developing', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
